-- 1. Tabla de Categorías
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null unique,
  image_url text,
  is_active boolean default true
);

-- 2. Tabla de Productos
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price decimal(10,2) not null,
  old_price decimal(10,2),
  stock integer default 0, -- Solo visible por Admin
  image_url text,
  category_id bigint references public.categories(id),
  brand text,
  is_new boolean default false,
  sku text
);

-- 3. Habilitar RLS (Seguridad a nivel de fila)
alter table public.categories enable row level security;
alter table public.products enable row level security;

-- 4. Políticas de Acceso (Policies)

-- Categorías: Cualquiera puede ver (Select Public)
create policy "Categorías visibles para todos"
  on public.categories for select
  using ( true );

-- Productos: Cualquiera puede ver (Select Public)
create policy "Productos visibles para todos"
  on public.products for select
  using ( true );

-- Admin: Permitir todo (Insert/Update/Delete)
-- Nota: El "Backend" usa la SERVICE_ROLE_KEY que se salta estas reglas,
-- pero es bueno tenerlas por si usas el cliente en el frontend para admins.
-- Por ahora, dejaremos lectura pública y escritura solo backend (implicitamente).

-- 5. Storage (Almacenamiento de Imágenes)
-- Crear bucket público 'products'
insert into storage.buckets (id, name, public)
values ('products', 'products', true);

-- Policy: Cualquiera puede ver imágenes (Public Read)
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'products' );

-- Policy: Solo autenticados pueden subir (Authenticated Upload)
create policy "Authenticated Upload"
on storage.objects for insert
with check ( bucket_id = 'products' and auth.role() = 'authenticated' );

-- Policy: Solo autenticados pueden actualizar/borrar
create policy "Authenticated Update"
on storage.objects for update
using ( bucket_id = 'products' and auth.role() = 'authenticated' );

create policy "Authenticated Delete"
on storage.objects for delete
using ( bucket_id = 'products' and auth.role() = 'authenticated' );

